version: '3.8'

services:
  cut-roll-movies:
    image: cut-roll-movies
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: movies_container
    environment:
      ASPNETCORE_URLS: http://+:80 
      POSTGRES_CONNECTION_STRING: "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=${POSTGRES_DB};Pooling=true;"

    ports:
      - 5000:80
    depends_on:
      - postgres
    networks:
      - microservices-network
    restart: always

  
  postgres:
    image: postgres:latest
    container_name: movies_db_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - microservices-network
    volumes:
      - movies_db_volume:/var/lib/postgresql/data
    restart: always

volumes:
  movies_db_volume:

networks:
  microservices-network:
    external: true

